language: ruby
rvm:
  - 2.4.2
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
before_script:
  - cp config/secrets.example.yml config/secrets.yml
  - psql -c 'create database ss_test;' -U postgres
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare --trace
script:
  - bundle exec rubocop
  - bundle exec rspec
  - yarn lint
