default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ss_development

test:
  <<: *default
  database: ss_test

production:
  <<: *default
  database: ss_production
  username: ss
  password: <%= ENV['SS_DATABASE_PASSWORD'] %>
